name: Blackduck Scan
on: workflow_call
jobs:
    Blackduck_scan_DOT-NET:
      if: ${{ vars.RDS_TECHNOLOGY == 'DOT-NET' }}
      runs-on: ubuntu-latest
      steps:
        - name: Running Blackduck scan for DOT-NET
          run: |
                   echo "hello"
                   echo "this will trigger when RDS_TECHNOLOGY variable is ${{ vars.RDS_TECHNOLOGY }}"


    Blackduck_scan_JAVA:
      if: ${{ vars.RDS_TECHNOLOGY == 'JAVA' }}
      runs-on: ubuntu-latest
      steps:
        - name: Running Blackduck scan for Java
          run: |
                   echo "hello"
                   echo "this will trigger when RDS_TECHNOLOGY variable is ${{ vars.RDS_TECHNOLOGY }}"

