name: first flow
#on: create
on: workflow_dispatch
jobs:
    Build:
      runs-on: $RUNNER_TAG
      steps:
          - run: |
                   echo "hello"
                   echo "this is triggered when you create a tag"

